@host=http://localhost:8080


GET {{host}}/
###`
GET {{host}}/api/anggota
###
GET {{host}}/api/anggota/search?q=A003
###
GET {{host}}/api/buku
###
GET {{host}}/api/buku/5
###
DELETE {{host}}/api/anggota/29
###
POST {{host}}/api/pinjaman
Content-Type: application/json

{
    
    "anggota_id":45,
    "buku_id":18,
    
    "petugas_pinjam_id":null,
    "petugas_balik_id":null,
    "kondisi_awal_id":1,
    "kondisi_akhir_id":1,
    "status":"dipinjam"
}
###
POST {{host}}/api/petugas
Content-Type: application/json

{
    "anggota_id":8,
}
###
POST {{host}}/api/buku
Content-Type: application/json

{
    "judul":"bulan",
    "list_kategori_id":2,
    "stock":400,
    "penulis": "tes"
}
###
PUT {{host}}/api/petugas/1
Content-Type: application/json

{
    "anggota_id":9
}

###
GET {{host}}/api/buku/search?q=B003
###
GET {{host}}/api/buku-hub/2
###
DELETE {{host}}/api/harga-buku/2
###
GET {{host}}/api/denda
###
POST  {{host}}/api/denda
Content-Type: application/json

{
  "petugas_id":1,
  "list_kondisi_id": 2,
  "total_hari": 3,
  "denda":19,
  "harga_buku_id": 1,
  "total_denda": 10,
}
###
POST  {{host}}/api/klasifikasi-anggota
Content-Type: application/json

{
  "klasifikasi": "test",
  "maks_buku": 2,
  "maks_hari": 3,
}
###
GET {{host}}/api/buku-hub
###
GET {{host}}/api/list-kondisi
###
GET {{host}}/api/rak
###
GET {{host}}/api/anggota/A009
###
POST  {{host}}/api/buku-hub
Content-Type: application/json

{
    "barcode":"B003",
    "buku_id":18,
    "list_kondisi_id":1,
    "anggota_id":29,
    "rak_id":1
}

###
PUT {{host}}/api/buku/17
Content-Type: application/json

{
  "list_kondisi_id":1,
  "rak_id":1,
}